import { VisualScriptCommandSchema } from '../validators/timelineSchema.js';

/**
 * VisualScriptValidator v1.0
 * 
 * Ensures all visual actions generated by agents conform to the schema 
 * before being emitted via sockets.
 */
export function validateVisualScript(actions) {
  if (!Array.isArray(actions)) return [];

  return actions.filter(action => {
    try {
      VisualScriptCommandSchema.parse(action);
      return true;
    } catch (err) {
      console.warn(`[Validator] Dropping malformed action:`, action, err.message);
      return false;
    }
  });
}
